### ISSUE TITLE
Browse Views Not Rendering Properly

### ISSUE THREAD

**Issue by sdfb** [sdfb/sdfb#294]
http://www.sixdegreesoffrancisbacon.com/people/1
http://www.sixdegreesoffrancisbacon.com/relationships/1
<img width="1190" alt="screenshot" src="https://user-images.githubusercontent.com/6977267/35917163-15c8801c-0bdb-11e8-8e8e-125c68dc68f5.png">

**Comment by jrladd** [comment]
I just fixed this one—it has to do with the way the app looks for CSS styles in our `dist/index.html`. For some reason the `grunt build` command that we run when the code updates doesn't automatically add a slash before the filepaths for styles. It's very easy to fix manually, but it does need to be done every time the code updates.
